basePath: /
definitions:
  database.ActionStore:
    properties:
      actionId:
        type: integer
      address:
        type: string
      name:
        type: string
      point:
        type: integer
      time:
        type: string
    type: object
  database.NFTStore:
    properties:
      address:
        type: string
      cid:
        type: string
      time:
        type: string
      tokenId:
        type: integer
      type:
        type: string
    type: object
  types.ListNFTRes:
    properties:
      nftInfos:
        items:
          $ref: '#/definitions/database.NFTStore'
        type: array
    type: object
  types.ListProjectsRes:
    properties:
      projects:
        items:
          $ref: '#/definitions/types.ProjectInfo'
        type: array
    type: object
  types.MintRes:
    properties:
      tokenID:
        type: integer
    type: object
  types.PointHistoryRes:
    properties:
      history:
        items:
          $ref: '#/definitions/database.ActionStore'
        type: array
    type: object
  types.PointInfoRes:
    properties:
      charging:
        type: boolean
      chargingCount:
        type: integer
      godataCount:
        type: integer
      godataSpace:
        type: integer
      points:
        type: integer
    type: object
  types.ProjectInfo:
    properties:
      end:
        type: string
      name:
        type: string
      projectID:
        type: integer
      start:
        type: string
    type: object
  types.RankInfo:
    properties:
      address:
        type: string
      points:
        type: integer
      rank:
        type: integer
      scores:
        type: integer
    type: object
  types.RankRes:
    properties:
      rankInfo:
        items:
          $ref: '#/definitions/types.RankInfo'
        type: array
    type: object
  types.TweetNFTInfoRes:
    properties:
      images:
        items:
          type: string
        type: array
      name:
        type: string
      postTime:
        type: integer
      tweet:
        type: string
    type: object
  types.UserInfoRes:
    properties:
      address:
        type: string
      inviteCode:
        type: string
      invitedCode:
        type: string
      points:
        type: integer
      referrals:
        type: integer
      space:
        type: integer
    type: object
host: test-xs-api.memolabs.net
info:
  contact: {}
  description: This is the API document for xspace server.
  title: Xspace-Server API
  version: "1.0"
paths:
  /v1/challenge:
    get:
      consumes:
      - application/json
      description: Get the challenge message by address before you login
      parameters:
      - description: User's address (connect to xspace)
        in: query
        name: address
        required: true
        type: string
      - description: The network ID which the user's wallet is connected to
        in: query
        name: chainid
        required: true
        type: string
      - description: The frontend's domain
        in: header
        name: Origin
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: The challenge message
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
      tags:
      - Login
  /v1/login:
    post:
      consumes:
      - application/json
      description: |-
        Use the signMessage method to sign the challenge message. After signing, call the login interface to complete the login.
        If the login is successful, the Login API will return an Access Token and a Refresh Token. When accessing subsequent APIs, you need to add the Authorization field in the headers with the value "Bearer Your_Access_Token"
      parameters:
      - description: The challenge message
        in: body
        name: message
        required: true
        schema:
          type: string
      - description: The result after the user's private key signs the challenge message
        in: body
        name: signature
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: The access token and refresh token
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
      tags:
      - Login
  /v1/nft/data/info:
    get:
      consumes:
      - application/json
      description: Get DataNFT content
      parameters:
      - description: Bearer YOUR_ACCESS_TOKEN
        in: header
        name: Authorization
        required: true
        type: string
      - description: DataNFT's id
        in: query
        name: tokenID
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: DataNFT binary content
          schema:
            type: file
        "400":
          description: Bad Request
          schema: {}
        "403":
          description: Forbidden
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - NFT
  /v1/nft/data/mint:
    post:
      consumes:
      - multipart/form-data
      description: Mint user's data into NFTs
      parameters:
      - description: Bearer YOUR_ACCESS_TOKEN
        in: header
        name: Authorization
        required: true
        type: string
      - description: User's data
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.MintRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - NFT
  /v1/nft/list:
    get:
      consumes:
      - application/json
      description: List all NFT information belonging to the user
      parameters:
      - description: Bearer YOUR_ACCESS_TOKEN
        in: header
        name: Authorization
        required: true
        type: string
      - description: Pages
        in: query
        name: page
        required: true
        type: string
      - description: The amount of data displayed on each page
        in: query
        name: size
        required: true
        type: string
      - description: NFT type (tweet for tweetNFT, data for dataNFT, tweetNFT and
          dataNFT will be all listed by default)
        in: query
        name: type
        type: string
      - description: Order rules (date_asc for sorting by creation time from smallest
          to largest, date_desc for sorting by creation time from largest to smallest,
          dealut is date_desc)
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ListNFTRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - NFT
  /v1/nft/tweet/info:
    get:
      consumes:
      - application/json
      description: Get TweetNFT content
      parameters:
      - description: Bearer YOUR_ACCESS_TOKEN
        in: header
        name: Authorization
        required: true
        type: string
      - description: TweetNFT's id
        in: query
        name: tokenID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.TweetNFTInfoRes'
        "400":
          description: Bad Request
          schema: {}
        "403":
          description: Forbidden
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - NFT
  /v1/nft/tweet/mint:
    post:
      consumes:
      - application/json
      description: Mint user's tweets into NFTs
      parameters:
      - description: Bearer YOUR_ACCESS_TOKEN
        in: header
        name: Authorization
        required: true
        type: string
      - description: User's twtter/x name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: The timestamp when the user posted the tweet
        in: body
        name: postTime
        required: true
        schema:
          type: integer
      - description: The text of the tweet(including emoji)
        in: body
        name: tweet
        required: true
        schema:
          type: string
      - description: The image url of the tweet
        in: body
        name: images
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.MintRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - NFT
  /v1/point/add:
    post:
      consumes:
      - application/json
      description: Users can earn point with finish action
      parameters:
      - description: Bearer YOUR_ACCESS_TOKEN
        in: header
        name: Authorization
        required: true
        type: string
      - description: action id (101 for follow twitter, 102 for follow discord, 103
          for follow telegram)
        in: body
        name: actionId
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.UserInfoRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - Point
  /v1/point/charge:
    post:
      consumes:
      - application/json
      description: Users can charge once every 6 hours
      parameters:
      - description: Bearer YOUR_ACCESS_TOKEN
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.UserInfoRes'
        "403":
          description: Forbidden
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - Point
  /v1/point/history:
    get:
      consumes:
      - application/json
      description: Get the history of the point info by address
      parameters:
      - description: Bearer YOUR_ACCESS_TOKEN
        in: header
        name: Authorization
        required: true
        type: string
      - description: Pages
        in: query
        name: page
        required: true
        type: string
      - description: The amount of data displayed on each page
        in: query
        name: size
        required: true
        type: string
      - description: The action id
        in: query
        name: actionID
        type: string
      - description: Order rules (date_asc for sorting by creation time from smallest
          to largest, date_desc for sorting by creation time from largest to smallest,
          dealut is date_desc)
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.PointHistoryRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - Point
  /v1/point/info:
    get:
      consumes:
      - application/json
      description: Get the user's point info by address
      parameters:
      - description: Bearer YOUR_ACCESS_TOKEN
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.PointInfoRes'
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - User
  /v1/point/invite:
    post:
      consumes:
      - application/json
      description: Get the history of the point info by address
      parameters:
      - description: Bearer YOUR_ACCESS_TOKEN
        in: header
        name: Authorization
        required: true
        type: string
      - description: The invite code from other user
        in: body
        name: code
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.UserInfoRes'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - Point
  /v1/project/list:
    get:
      consumes:
      - application/json
      description: List all projects with Xspace
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ListProjectsRes'
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - Rank
  /v1/project/rank:
    get:
      consumes:
      - application/json
      description: Get the ranking of cooperative projects
      parameters:
      - description: cooperative project id
        in: query
        name: id
        required: true
        type: string
      - description: Pages
        in: query
        name: page
        required: true
        type: string
      - description: The amount of data displayed on each page
        in: query
        name: size
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.RankRes'
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - Rank
  /v1/refresh:
    post:
      consumes:
      - application/json
      description: If the access token expires, you can call the refresh API to get
        a new access token or log in again.
      parameters:
      - description: Bearer YOUR_FRESH_TOKEN
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: The access token
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema: {}
      tags:
      - Login
  /v1/user/info:
    get:
      consumes:
      - application/json
      description: Get the user basic info by address
      parameters:
      - description: Bearer YOUR_ACCESS_TOKEN
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.UserInfoRes'
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - User
swagger: "2.0"
